### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'password'

### ISSUE THREAD

**Issue by yoshifan509** [lingthio/Flask-User#238]
Happens if I delete the DB file. Works if I leave it alone for a few.
Nothing with variables, this is all something with Flask-User
Full Traceback:
```
Traceback (most recent call last):
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/environment/AmusedGrape/ask/server.py", line 128, in home_page
    return render_template('index.html')
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/templating.py", line 133, in render_template
    ctx.app.update_template_context(context)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 792, in update_template_context
    context.update(func())
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_login/utils.py", line 368, in _user_context_processor
    return dict(current_user=_get_user())
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_user/user_manager.py", line 130, in load_user_by_user_token
    user = self.db_manager.UserClass.get_user_by_token(user_token)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_user/user_mixin.py", line 52, in get_user_by_token
    user_password = '' if user_manager.USER_ENABLE_AUTH0 else user.password[-8:]
AttributeError: 'NoneType' object has no attribute 'password'
```

**Comment by yoshifan509** [comment]
Can confirm,**This is an issue with Flask-User.**

**Comment by yoshifan509** [comment]
Everything works if I remove the UserManager class from my code. It is an issue with Flask-User.

**Comment by lingthio** [comment]
I've been a bit swamped lately. Care to submit a fix as a pull request? -- Ling

**Comment by saitam1** [comment]
@yoshifan509 which Python version are you using?

**Comment by saitam1** [comment]
It happens when you delete a user from the database and then reload the url you are in or even the base url for the website

**Comment by yoshifan509** [comment]
@saitam1 I am using 3.6.5.
I'll try to delete the session cookies.
I cleared the browser cookies and that seemed to fix it.

**Comment by bkgoodman** [comment]
Deleting cookies worked for me - but _really_ should be fixed for "real".

**Comment by papak69** [comment]
is there anyway i can "force" delete cookie for user if the user was deleted from db?

**Comment by colaisr** [comment]
confirm it still happens ...when removing db.. but not everytime...first time a day after several deletes redos

**Comment by wenjie0909** [comment]
Hi,

I just change the code in user_mixin.py as following, and it seems works:

after: user_password = '' if user_manager.USER_ENABLE_AUTH0 or user == None else user.password[-8:]
before: user_password = '' if user_manager.USER_ENABLE_AUTH0  else user.password[-8:]
